package App;

import org.json.JSONObject;
import yunxin.Token;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws Exception {
        Token yunToken = new Token();
        JSONObject token = yunToken.getToken();
        System.out.println(token);
    }
}
